- name: Install all updates
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  register: result

- name: List installed and updated packages
  become: true
  shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log | cut -d " " -f 3-5
  register: package_list
  ignore_errors: true

- name: Show output
  debug:
    msg: "installed packages: {{ package_list.stdout_lines }}"

- name: Print error message if update fails
  debug:
    msg: "{{ result.msg }}"
  when: result.failed

- name: Create the security.sources.list file
  shell: |
    grep security /etc/apt/sources.list > /etc/apt/security.sources.list

- name: Install just security updates
  apt:
    upgrade: yes
    dpkg_options: "Dir::Etc::SourceList=/etc/apt/security.sources.list"
  register: apt_output

- name: Confirm patch
  debug: 
    msg:"Patch completed succefully"
  when: result.succeed
  register: patch_output 

- name: check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: check if reboot is nedded true or false
  debug:
    msg: "reboot is {{ reboot_required_file.stat.exists  | ternary('NEEDED', 'NOT NEDDED') }} "
  register: rebout_output 

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
  reboot_timeout: 300