- hosts: all
  become: true
  tasks:
   # - name: List available updates
   # command: yum check-update
   # register: yum_update_output_before
    
    #- name: msg
    # debug:
    #   msg: "Available updates list"

    - name: Perform updates from local repository
      yum:
        name: '*'
      # exclude: "name the packages that you dont want to update"
        state: latest
        security: critical 
      register: result

    - name: msg
      debug:
        msg: "Patch performed successfully"
      when: result.succeed
      register: result_output 

      #Add else  IF THE PATCH WAS NOT PERFORMED 

  #  - name: List installed and updated packages
  #    shell: yum list installed | cut -d' ' -f1
  #    register: package_list
  #    ignore_errors: true

    - name: Run needs-restarting command
      command: needs-restarting -r
      register: reboot_check
      changed_when: false
      failed_when: false

    - name: Display reboot status
      debug:
        msg: "Reboot is {{ 'NEEDED' if reboot_check.stdout != '' else 'NOT NEEDED' }}"
      register: reboot_status

    - name: Reboot if required
      reboot:
        when: reboot_check.stdout == '1'
        reboot_timeout: 300
