- hosts: all
  become: true
  tasks:
    - name: List available updates
      command: yum check-update
      register: yum_update_output_before
    
    - name: msg
      debug:
        msg: "Available updates list"

    - name: Perform updates from local repository
      yum:
        name: '*'
        state: latest
    
    - name: msg
      debug:
        msg: "Patch performed successfully"

    - name: Check if reboot is needed
      shell:
        cmd: /usr/bin/needs-restarting -r
      register: needs_restarting
      changed_when: False
      failed_when: False

    - name: List available updates after reboot
      command: yum check-update
      register: yum_update_output_after

    - name: Generate and send report
      shell:
        cmd: |
          echo "Report for Red Hat VM patching:" > Redhat_report.txt
          echo "Updates listed before executing the playbook: '{{ yum_update_output_before }}'" >> Redhat_report.txt
          echo "Updates installed from local repo: '{{ yum_update_output_after }}'" >> Redhat_report.txt
          mail -s "Red Hat VM patching report" yboukari@deloitte.fr < Redhat_report.txt
