---
- name: Configure apt-cacher-ng server
  hosts: target_vm
  become: true

  tasks:
  - name: 
  - name: Edit 00aptproxy file to use apt-cacher-ng server
    blockinfile:
      path: /etc/apt/apt.conf.d/00aptproxy
      block: |
        Acquire::http::Proxy "http://my-apt-cacher-ip:3142/";

