- hosts: all
  ignore_unreachable: true
  become: true
  tasks:
        
    # Fix OS release version before patching???
    
    - name: In case of playbook failure
      fail: 
        msg: "{{ playbook_name }} failed because of {{update_result}}. Please review the logs, then attempt patching.
                 The command {{ update_result.cmd/sec_patch_result.cmd }} failed with return code {{ sec_patch_result.rc/update_result.rc }}"
      when: update_result.failed/sec_patch_result.failed

    - name: Confirm patch
      debug: 
        msg:"Patch completed succefully"

    - name: check if reboot is needed
      stat:
         path: /var/run/reboot-required
      register: reboot_required_file
  

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
      reboot_timeout: 300

    - name: List available updates after reboot
      command: apt list --upgradable
      register: apt_list_output_after



     

